# Generated by Django 4.2.30 on 2026-05-10 19:22

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Ticket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the person raising the ticket.",
                        max_length=100,
                        validators=[django.core.validators.MinLengthValidator(2)],
                    ),
                ),
                (
                    "area",
                    models.CharField(
                        choices=[
                            ("engineering", "Engineering"),
                            ("technology", "Technology"),
                            ("ops", "Ops"),
                            ("strategy", "Strategy"),
                            ("support", "Support"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("able", "Able to work"),
                            ("partial", "Partially able to work"),
                            ("not_able", "Not able to work"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Describe the problem in at least 10 characters.",
                        validators=[django.core.validators.MinLengthValidator(10)],
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("opened", "Opened"),
                            ("assigned", "Assigned"),
                            ("working", "Working"),
                            ("closed", "Closed"),
                        ],
                        default="opened",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "submitted_by",
                    models.ForeignKey(
                        help_text="The account that submitted this ticket (used for ownership checks).",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tickets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status"], name="tickets_tic_status_0e5646_idx"
                    ),
                    models.Index(
                        fields=["submitted_by", "-created_at"],
                        name="tickets_tic_submitt_b6f001_idx",
                    ),
                ],
            },
        ),
    ]
